-- Run with a role permitted to create the demo database/warehouse.
-- No personal applicant records or raw audio are stored.
CREATE DATABASE IF NOT EXISTS PASSITON;
CREATE WAREHOUSE IF NOT EXISTS PASSITON_WH WITH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE INITIALLY_SUSPENDED=TRUE;
CREATE ROLE IF NOT EXISTS PASSITON_APP;
CREATE TABLE IF NOT EXISTS PASSITON.PUBLIC.PASSITON_EVENTS (ID VARCHAR NOT NULL, PAYLOAD VARIANT NOT NULL, CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP());
CREATE TABLE IF NOT EXISTS PASSITON.PUBLIC.PASSITON_QUESTIONS (ID VARCHAR NOT NULL, TITLE VARCHAR NOT NULL);
MERGE INTO PASSITON.PUBLIC.PASSITON_QUESTIONS t USING (
 SELECT column1 ID, column2 TITLE FROM VALUES
 ('provisional','Can I apply before my final results?'),
 ('documents','Which documents do I need?'),
 ('submission','How do I submit my application?')
) s ON t.ID=s.ID WHEN NOT MATCHED THEN INSERT (ID,TITLE) VALUES (s.ID,s.TITLE);
GRANT USAGE ON WAREHOUSE PASSITON_WH TO ROLE PASSITON_APP;
GRANT USAGE ON DATABASE PASSITON TO ROLE PASSITON_APP;
GRANT USAGE ON SCHEMA PASSITON.PUBLIC TO ROLE PASSITON_APP;
GRANT SELECT, INSERT ON TABLE PASSITON.PUBLIC.PASSITON_EVENTS TO ROLE PASSITON_APP;
GRANT SELECT ON TABLE PASSITON.PUBLIC.PASSITON_QUESTIONS TO ROLE PASSITON_APP;
-- Attach PASSITON_APP to the dedicated service user with an RSA public key.
-- Never put a user password in Vercel. The app uses the SQL API with key-pair auth.
